/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "load.h"

bool_t
xdr_data (XDR *xdrs, data *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->text, 1024))
		 return FALSE;
	return TRUE;
}
