/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _LOAD_H_RPCGEN
#define _LOAD_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct data {
	char *text;
};
typedef struct data data;

#define LOAD_PROG 123456789
#define LOAD_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define GET_LOAD 1
extern  struct data * get_load_1(struct data *, CLIENT *);
extern  struct data * get_load_1_svc(struct data *, struct svc_req *);
extern int load_prog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define GET_LOAD 1
extern  struct data * get_load_1();
extern  struct data * get_load_1_svc();
extern int load_prog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_data (XDR *, data*);

#else /* K&R C */
extern bool_t xdr_data ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_LOAD_H_RPCGEN */
